os:
  - linux

sudo: false

branches:
  only:
  - master

env:
  global:
    - GRADLE_OPTS="-Xms256m -Xmx384m"
    - JAVA_SOLUTION_PATH=$TRAVIS_BUILD_DIR/java-algorithm
    - PYTHON_SOLUTION_PATH=$TRAVIS_BUILD_DIR/python-algorithm

matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - cd $PYTHON_SOLUTION_PATH && pip3 install -r requirements.txt
      script: cd $PYTHON_SOLUTION_PATH && pytest
    - language: java
      jdk: openjdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      script: cd $JAVA_SOLUTION_PATH && ./gradlew clean build test
